name: Publish Utility Images
on:
  push:
    tags:
      - "utils/**/v[0-9]*"

jobs:
  publish:
    name: Publish
    runs-on: buildjet-4vcpu-ubuntu-2204
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          buildkitd-flags: "--debug"
      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set image and tag
        run: ./scripts/setup_tags.sh
      - name: Build and Publish Docker Images
        run: |
          docker buildx build --push --platform linux/amd64,linux/arm64 --tag ghcr.io/acorn-io/aws/${IMAGE}:${TAG} ./${IMAGE}
